# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='文章摘要'),
        ),
    ]
