# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171201_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textfield', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
